config/routes.rb
Rails.application.routes.draw do
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #   get 'cocktails', to: 'cocktails#index'
  #   get 'cocktail', to: 'cocktails#show'
  root to: "cocktails#index"
  resources :cocktails, only: [:new, :create, :show, :index, :destroy] do
    resources :doses, only: [:new, :create, :show]
  end
  resources :doses, only: [:destroy]
  resources :ingredients, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :ingredient, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :cocktails, through: :doses
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    # => Whitelisting
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
    @doses = Dose.all
  end

  def show
    @dose = Dose.find(params[:cocktail_id])
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  def dose_params
    # => Whitelisting
    params.require(:dose).permit(:ingredient_id, :description)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Cocktail.all
  end
  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to cocktails_path
    else
      render 'new'
    end
  end

  private

  def ingredient_params
    # => Whitelisting
    params.require(:ingredient).permit(:name)
  end

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<% @cocktails.each do |cocktail|%>
<div class="card-product cocktails">
  <%= cl_image_tag cocktail.photo, height: 300, width: 400, crop: :fill %>
  <div style="width: 18rem;">
    <h2 ><%= cocktail.name %></h2>
    <p><%=  link_to "Details", cocktail_path(cocktail)%> </p>
    <p> <%= link_to "🗑",  cocktail_path(cocktail), method: :delete, data:{confirm:"U sure ?"}%></p>
  </div>
</div>
<% end %>

app/views/cocktails/new.html.erb
<h1>Add a new cocktail</h1>
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<div class="lower-banner"><h1><%= @cocktail.name %></h1>
  <p><%= link_to "Back to cocktails !", cocktails_path %></p>
</div>
<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
<h4>Ingredients & doses:</h4>
<ol>
  <p><% @cocktail.doses.each do |dose| %></p>
  <li>
    <span><strong><%= dose.ingredient.name.capitalize %></strong> -
    <%= dose.description.capitalize %>
    <%= link_to "🗑", dose_path(dose), method: :delete, data:{confirm:"U sure ?"} %></span>

  <% end %>
  </li>
</ul>

<p><%= link_to "Add a new dose", new_cocktail_dose_path(@cocktail) %></p>

app/views/doses/new.html.erb
<h1>Add a new dose in <%= @cocktail.name %></h1>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description %>

  <%= f.submit %>
<% end %>

app/views/ingredients/new.html.erb
<h1>Add a new ingredient</h1>
<%= simple_form_for (@ingredient) do |f| %>

  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="favicon.ico" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1440,w_2560,x_0,y_0/dpr_1.5/c_limit,w_1044/fl_lossy,q_auto/v1517521303/180131-wondrich-bad-cocktail-tease_wghhv8);">
  <div class="container banner">

    <h1>Welcome to Lisa's Cocktails</h1>

    <a class="btn btn-flat" href="#"> <h4><%= link_to "All cocktails",  cocktails_path %></h4></a>
    <a class="btn btn-flat" href="#"> <h4><%= link_to "Add cocktail", new_cocktail_path %></h4></a>
    <a class="btn btn-flat" href="#"> <h4><%= link_to "Add an ingredient", new_ingredient_path %></h4></a>
  </div>
</div>


    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
  </body>
</html>